// type 页面类型，1：首页，2：分类页，3：营销页，4：搜索页，5：详情页，6：其他，7：资讯分类页，8：资讯详情页，9咨询头条页，10：品牌首页，11：店铺首页，12：店铺营销页，13：积分商城分类页，14：登录页，15：注册页，16：个人中心，17：购物车 18: 积分商城首页
const pages = [{
  'codeList': [
    'title',
    'search',
    'slider',
    'video',
    'rich-text',
    'cube',
    'h5-multipic',
    'slide-show',
    'img-map',
    'bulletin',
    'goods-recommend',
    'spacing',
    'goods-r1c1b',
    'goods-r1c1s',
    'goods',
    'goods-r1c3',
    'goods-r1cn',
    'count-down',
    'rank-landing-page',
    'multi-coupons',
    'channel',
    'tabs',
    'header'
  ],
  'label': '首页',
  'type': 1,
  'value': 'home'
}, {
  'codeList': [
    'title',
    'search',
    'slider',
    'video',
    'rich-text',
    'cube',
    'h5-multipic',
    'slide-show',
    'img-map',
    'bulletin',
    'goods-recommend',
    'spacing',
    'goods-r1c1b',
    'goods-r1c1s',
    'goods',
    'goods-r1c3',
    'goods-r1cn',
    'count-down',
    'rank-landing-page',
    'multi-coupons',
    'channel',
    'tabs',
    'header',
    'point-info'
  ],
  'label': '积分商城首页',
  'type': 18,
  'value': 'point-home'
}, {
  'codeList': [
    'title',
    'search',
    'slider',
    'video',
    'rich-text',
    'cube',
    'h5-multipic',
    'slide-show',
    'img-map',
    'bulletin',
    'goods-recommend',
    'spacing',
    'goods-r1c1b',
    'goods-r1c1s',
    'goods',
    'goods-r1c3',
    'goods-r1cn',
    'count-down',
    'rank-landing-page',
    'multi-coupons',
    'channel',
    'tabs',
    'header'
  ],
  'label': '店铺首页',
  'type': 11,
  'value': 'store-home'
}, {
  'codeList': [
    'title',
    'search',
    'slider',
    'video',
    'rich-text',
    'cube',
    'h5-multipic',
    'slide-show',
    'img-map',
    'bulletin',
    'goods-recommend',
    'spacing',
    'goods-r1c1b',
    'goods-r1c1s',
    'goods',
    'goods-r1c3',
    'goods-r1cn',
    'count-down',
    'rank-landing-page',
    'multi-coupons',
    'channel',
    'tabs',
    'header'
  ],
  'label': '营销页',
  'type': 3,
  'value': 'promotion'
},
{
  'codeList': [
    'video',
    'rich-text',
    'h5-multipic',
    'spacing',
    'goods-r1c1s'
  ],
  'label': '资讯详情页',
  'type': 8,
  'value': 'informationDetails'
}
]
export default pages
